### ISSUE TITLE
One entrypoint on spark_forecast.tasks.model

### ISSUE THREAD

**Issue by dgarridoa** [dgarridoa/spark-forecast#37]
Instead of having multiples entrypoint from the spark_forecast.tasks.model module just have one. Based on different arguments this unique entrypoint will pick a Darts model class. 

The model tasks on the databricks.yml would be:
```
- task_key: "exponential_smoothing"
  depends_on:
    - task_key: "split"
  job_cluster_key: "${bundle.target}-${bundle.name}-job-cluster"
  python_wheel_task:
    package_name: "spark_forecast"
    entry_point: "model"
    parameters:
    - "--conf-file"
    - "/Workspace${workspace.root_path}/files/conf/tasks/exponential_smoothing_config.yml"
    - "--env"
    - "${bundle.target}"
- task_key: "moving_average"
  depends_on:
    - task_key: "split"
  job_cluster_key: "${bundle.target}-${bundle.name}-job-cluster"
  python_wheel_task:
    package_name: "spark_forecast"
    entry_point: "model"
    parameters:
    - "--conf-file"
    - "/Workspace${workspace.root_path}/files/conf/tasks/moving_average_config.yml"
    - "--env"
    - "${bundle.target}"
  ```
  
  
And the task config yml would be:
```
...
model_name: "ExponentialSmoothing"
model_params:
  seasonal_periods: 7
```
